### ISSUE TITLE
[XML] Create XML extractor

### ISSUE THREAD

**Issue by vinzcoco** [camillebaronnet/php-etl-framework#9]

**Comment by camillebaronnet** [comment]
I think it's not relevant to basically create an XML extractor, because it is an XML extractor what source?
For example, the generic REST extractor I'm working on integrates decoding of Json, Xml, CSV and Yaml. (yes I use the symfony/serializer).

**Comment by camillebaronnet** [comment]
I'll remove the CSV extractor,
Also you can see the #1 and #6  issues

**Comment by vinzcoco** [comment]
Ok also you can used Symfony serializer. It's very useful for implement encoders (json, xml, csv, ...)
